version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.3'
    container_name: kaldb_zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.2.3'
    container_name: kaldb_kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://127.0.0.1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=test-topic:1:1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  grafana:
    image: 'grafana/grafana:8.5.3'
    container_name: kaldb_grafana
    ports:
      - '3000:3000'
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ../slack-kaldb-app:/var/lib/grafana/plugins
    environment:
      GF_LOG_MODE: "console file"
      GF_LOG_LEVEL: "info"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PLUGINS: "/var/lib/grafana/plugins"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "slack-kaldb-app,slack-kaldb-app-backend-datasource"

  mock-s3:
    image: 'adobe/s3mock:2.11.0'
    container_name: kaldb_s3
    ports:
      - 9090:9090
      - 9191:9191
    environment:
      - initialBuckets=test-s3-bucket
      - root=/tmp/s3mock
      - debug=true

  openzipkin:
    image: 'openzipkin/zipkin-slim'
    container_name: openzipkin
    ports:
      - 9411:9411

  trino:
    image: 'trino:408-SNAPSHOT-amd64'
    container_name: trino_trino
    profiles:
      - trino
    ports:
      - 8090:8080
    depends_on:
      - kaldb

  #to build this image run 'docker build -t slackhq/kaldb .'
  kaldb:
    image: 'slackhq/kaldb'
    container_name: kaldb_kaldb
    profiles:
      - kaldb
      - trino
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8085:8085
      - 8086:8086
    environment:
      - KALDB_ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - S3_ENDPOINT=http://mock-s3:9090
      - ZIPKIN_TRACING_ENDPOINT=http://openzipkin:9411/api/v2/spans
    depends_on:
      - zookeeper
      - kafka
      - mock-s3
      - openzipkin